/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    brands: Brand;
    products: Product;
    fields: Field;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    fields: FieldsSelect<false> | FieldsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Ürün kategorileri (hiyerarşik)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Kategori adı (çok dilli)
   */
  name: string;
  /**
   * SEO dostu URL (benzersiz)
   */
  slug: string;
  /**
   * Üst kategori (boş bırakırsanız ana kategori olur)
   */
  parent?: (number | null) | Category;
  /**
   * Kategori için temsilî görsel
   */
  image?: (number | null) | Media;
  /**
   * Kategori açıklaması (isteğe bağlı)
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Kategori yayın durumu
   */
  status?: ('active' | 'inactive') | null;
  /**
   * Meta başlık (60 karakter)
   */
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * Sıralama (küçük sayı önce gösterilir)
   */
  displayOrder?: number | null;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Ürün markaları
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  slug: string;
  /**
   * Marka logosu (önerilen boyut: 200x200)
   */
  logo?: (number | null) | Media;
  /**
   * Resmî web sitesi
   */
  website?: string | null;
  /**
   * Merkez ülke
   */
  country?: string | null;
  /**
   * Marka hakkında detaylı bilgi
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Marka yayın durumu
   */
  status?: ('active' | 'inactive') | null;
  /**
   * Sosyal medya hesapları (JSON formatında: { "instagram": "...", "twitter": "..." })
   */
  socialMedia?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Ürün yönetimi için kapsamlı koleksiyon örneği
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Ürünün görünen adı
   */
  name: string;
  /**
   * SEO dostu URL (benzersiz)
   */
  slug: string;
  /**
   * Detaylı ürün açıklaması
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Ürün fiyatı (TL)
   */
  price: number;
  /**
   * İndirimli fiyat (opsiyonel)
   */
  compareAtPrice?: number | null;
  /**
   * Mevcut stok adedi
   */
  stock: number;
  /**
   * Ürünün bağlı olduğu kategori
   */
  category: number | Category;
  /**
   * Ürün markası
   */
  brand?: (number | null) | Brand;
  /**
   * Ürün yayın durumu
   */
  status?: ('draft' | 'published' | 'archived') | null;
  /**
   * Öne çıkarılan ürün
   */
  featured?: boolean | null;
  /**
   * En fazla 5 görsel ekleyebilirsiniz
   */
  images?:
    | {
        image: number | Media;
        /**
         * SEO için alternatif metin
         */
        altText?: string | null;
        isMain?: boolean | null;
        id?: string | null;
      }[]
    | null;
  specs?: {
    weight?: number | null;
    dimensions?: {
      width?: number | null;
      height?: number | null;
      depth?: number | null;
    };
    colorOptions?:
      | {
          color: string;
          hexCode?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  contentBlocks?:
    | (
        | {
            heading?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            new?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            videoUrl: string;
            thumbnail?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoBlock';
          }
      )[]
    | null;
  /**
   * Ürün için ek meta veriler (JSON formatında)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Başlık etiketi (60 karakter)
   */
  metaTitle?: string | null;
  metaDescription?: string | null;
  keywords?: string | null;
  deliveryInfo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  warranty?: {
    duration?: number | null;
    description?: string | null;
  };
  /**
   * Benzersiz stok kodu
   */
  sku: string;
  /**
   * Barkod numarası
   */
  barcode?: string | null;
  /**
   * İç notlar (sadece admin görür)
   */
  notes?: string | null;
  internalTags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ürünün satışa çıkacağı tarih
   */
  availableFrom?: string | null;
  /**
   * Ürünün satıştan kalkacağı tarih
   */
  availableUntil?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * koleksiyon bazında yardımcı metin
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fields".
 */
export interface Field {
  id: number;
  /**
   * field bazında yardımcı metin
   */
  title: string;
  status?: ('draft' | 'published') | null;
  price: number;
  publishedAt?: string | null;
  detailText: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage: number | Media;
  faqItems?:
    | {
        question: string;
        answer?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  layout?:
    | (
        | {
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            image?: (number | null) | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
      )[]
    | null;
  jsonData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * şube açılış kapanış saatleri
   */
  workingHours?: {
    opening?: string | null;
    closing?: string | null;
  };
  heading?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  sample_grp?: {
    sample_one?: string | null;
    sample_two?: string | null;
  };
  mainColor: string;
  secondColor: string;
  language: string;
  secondLanguage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'fields';
        value: number | Field;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  image?: T;
  description?: T;
  status?: T;
  metaTitle?: T;
  metaDescription?: T;
  displayOrder?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  website?: T;
  country?: T;
  description?: T;
  status?: T;
  socialMedia?: T;
  email?: T;
  phone?: T;
  address?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  price?: T;
  compareAtPrice?: T;
  stock?: T;
  category?: T;
  brand?: T;
  status?: T;
  featured?: T;
  images?:
    | T
    | {
        image?: T;
        altText?: T;
        isMain?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        weight?: T;
        dimensions?:
          | T
          | {
              width?: T;
              height?: T;
              depth?: T;
            };
        colorOptions?:
          | T
          | {
              color?: T;
              hexCode?: T;
              id?: T;
            };
      };
  contentBlocks?:
    | T
    | {
        textBlock?:
          | T
          | {
              heading?: T;
              content?: T;
              new?: T;
              id?: T;
              blockName?: T;
            };
        imageBlock?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        videoBlock?:
          | T
          | {
              videoUrl?: T;
              thumbnail?: T;
              id?: T;
              blockName?: T;
            };
      };
  metadata?: T;
  metaTitle?: T;
  metaDescription?: T;
  keywords?: T;
  deliveryInfo?: T;
  warranty?:
    | T
    | {
        duration?: T;
        description?: T;
      };
  sku?: T;
  barcode?: T;
  notes?: T;
  internalTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  availableFrom?: T;
  availableUntil?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fields_select".
 */
export interface FieldsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  price?: T;
  publishedAt?: T;
  detailText?: T;
  featuredImage?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        textBlock?:
          | T
          | {
              heading?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        imageBlock?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  jsonData?: T;
  workingHours?:
    | T
    | {
        opening?: T;
        closing?: T;
      };
  heading?: T;
  body?: T;
  metaTitle?: T;
  metaDescription?: T;
  sample_grp?:
    | T
    | {
        sample_one?: T;
        sample_two?: T;
      };
  mainColor?: T;
  secondColor?: T;
  language?: T;
  secondLanguage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}